// Code generated by "stringer -output=enum_strings.go -type=Action"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionInvalid-0]
	_ = x[ActionCreateCard-1]
	_ = x[ActionInspectCard-2]
	_ = x[ActionPromptCard-3]
	_ = x[ActionGetAllCards-4]
	_ = x[ActionUpdateCard-5]
	_ = x[ActionUpdateCardPerformance-6]
	_ = x[ActionGetCardsToLearn-7]
	_ = x[ActionGetCardsToRepeat-8]
	_ = x[ActionGetSentences-9]
	_ = x[ActionGenerateStory-10]
	_ = x[ActionDeleteCard-11]
}

const _Action_name = "ActionInvalidActionCreateCardActionInspectCardActionPromptCardActionGetAllCardsActionUpdateCardActionUpdateCardPerformanceActionGetCardsToLearnActionGetCardsToRepeatActionGetSentencesActionGenerateStoryActionDeleteCard"

var _Action_index = [...]uint8{0, 13, 29, 46, 62, 79, 95, 122, 143, 165, 183, 202, 218}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
